# Generated by Django 3.0.3 on 2020-02-09 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200208_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnumber', models.CharField(blank=True, max_length=10, null=True)),
                ('carregistrationnumber', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.CarNumber'),
        ),
    ]
